spring.application.name=QuantityMeasurementApp
server.port=8080

# Repository Type (cache | database)
repository.type=database


# JPA CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 DATABASE (IN-MEMORY)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=username
spring.datasource.password=password

# CONNECTION POOL (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# LOGGING
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Custom log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %logger{5}:%line %msg%n

# SWAGGER / OPENAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ACTUATOR
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true